// Liste canonique des 66 livres (numero 1..66, Louis Segond). Utilisee par le
// formulaire de plan de lecture pour le perimetre "livres specifiques".
export const BIBLE_BOOKS = [
    { nr: 1, name: "Genese" },
    { nr: 2, name: "Exode" },
    { nr: 3, name: "Levitique" },
    { nr: 4, name: "Nombres" },
    { nr: 5, name: "Deuteronome" },
    { nr: 6, name: "Josue" },
    { nr: 7, name: "Juges" },
    { nr: 8, name: "Ruth" },
    { nr: 9, name: "1 Samuel" },
    { nr: 10, name: "2 Samuel" },
    { nr: 11, name: "1 Rois" },
    { nr: 12, name: "2 Rois" },
    { nr: 13, name: "1 Chroniques" },
    { nr: 14, name: "2 Chroniques" },
    { nr: 15, name: "Esdras" },
    { nr: 16, name: "Nehemie" },
    { nr: 17, name: "Esther" },
    { nr: 18, name: "Job" },
    { nr: 19, name: "Psaumes" },
    { nr: 20, name: "Proverbes" },
    { nr: 21, name: "Ecclesiaste" },
    { nr: 22, name: "Cantique des cantiques" },
    { nr: 23, name: "Esaie" },
    { nr: 24, name: "Jeremie" },
    { nr: 25, name: "Lamentations" },
    { nr: 26, name: "Ezechiel" },
    { nr: 27, name: "Daniel" },
    { nr: 28, name: "Osee" },
    { nr: 29, name: "Joel" },
    { nr: 30, name: "Amos" },
    { nr: 31, name: "Abdias" },
    { nr: 32, name: "Jonas" },
    { nr: 33, name: "Michee" },
    { nr: 34, name: "Nahum" },
    { nr: 35, name: "Habacuc" },
    { nr: 36, name: "Sophonie" },
    { nr: 37, name: "Aggee" },
    { nr: 38, name: "Zacharie" },
    { nr: 39, name: "Malachie" },
    { nr: 40, name: "Matthieu" },
    { nr: 41, name: "Marc" },
    { nr: 42, name: "Luc" },
    { nr: 43, name: "Jean" },
    { nr: 44, name: "Actes" },
    { nr: 45, name: "Romains" },
    { nr: 46, name: "1 Corinthiens" },
    { nr: 47, name: "2 Corinthiens" },
    { nr: 48, name: "Galates" },
    { nr: 49, name: "Ephesiens" },
    { nr: 50, name: "Philippiens" },
    { nr: 51, name: "Colossiens" },
    { nr: 52, name: "1 Thessaloniciens" },
    { nr: 53, name: "2 Thessaloniciens" },
    { nr: 54, name: "1 Timothee" },
    { nr: 55, name: "2 Timothee" },
    { nr: 56, name: "Tite" },
    { nr: 57, name: "Philemon" },
    { nr: 58, name: "Hebreux" },
    { nr: 59, name: "Jacques" },
    { nr: 60, name: "1 Pierre" },
    { nr: 61, name: "2 Pierre" },
    { nr: 62, name: "1 Jean" },
    { nr: 63, name: "2 Jean" },
    { nr: 64, name: "3 Jean" },
    { nr: 65, name: "Jude" },
    { nr: 66, name: "Apocalypse" },
];

export function bookName(nr) {
    const b = BIBLE_BOOKS.find((x) => x.nr === nr);
    return b ? b.name : `Livre ${nr}`;
}
